/*******************************************************************************
 * NFL Confidence Pool BE - the backend implementation of an NFL confidence pool.
 * Copyright (C) 2015-present Brian Duffey
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see {http://www.gnu.org/licenses/}.
 * Home: https://asitewithnoname.com/
 */
import { MigrationInterface, QueryRunner } from 'typeorm';

// ts-prune-ignore-next
export class InsertSupportContent1630265327824 implements MigrationInterface {
	public async up (queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`truncate table SupportContent`);
		await queryRunner.query(` INSERT INTO SupportContent (SupportContentType,SupportContentOrder,SupportContentDescription,SupportContentDescription2,SupportContentCategory,SupportContentKeywords,SupportContentAddedBy,SupportContentUpdatedBy) VALUES
        ('Rule',10,'Each pick must be submitted prior to the kickoff of the game. Any picks that were saved but not submitted will count, but all other empty picks count as zero points.','','',NULL,'BILLY','BILLY'),
        ('Rule',20,'In the event of a game ending in a tie, everyone loses that game.','','',NULL,'BILLY','BILLY'),
        ('Rule',30,'When making your picks for the week, you will notice a tie breaker box. This is always the final game of the week and your guess should be as close to the final total score (home team plus visiting team) without going over. This value is only used in the event of ties (see below). For example, if John Smith and Jane Doe both end a week with 90 points and 10 games correctly picked, then this value is used to see who was closest to the actual total points of the final game without going over. If John chose 30 and Jane chose 33 and the actual total was 32 (Home team: 20, Visitor: 12), then John is the winner for the week since he was close to 32 without going over.','','',NULL,'BILLY','BILLY'),
        ('Rule',40,'Payouts will be to the highest point total each week, as well as the top three point totals overall at the end of the regular season. In the event of a tie, the number of games correctly picked is the first tie breaker. In the event that is also even, then the tie breaker score of the final game of the week is used. In the event that is also a tie, the players will split the winnings.','','',NULL,'BILLY','BILLY'),
        ('Rule',50,'After you submit your selections or the week ends, and picks are no longer changeable, you may view other players'' picks.','','',NULL,'BILLY','BILLY'),
        ('Rule',60,'All players are welcome, please feel free to invite anyone who would enjoy participating. All $40 entry fees must be received by the end of the third week. New players will be accepted up until the start of the third week and will be assigned the current lowest point total.','','',NULL,'BILLY','BILLY'),
        ('Rule',70,'The maximum number of points in 16-game weeks is 136 points, 120 in 15-game weeks, 105 in 14-game weeks, and 91 in 13-game weeks.','','',NULL,'BILLY','BILLY'),
        ('Rule',80,'If the season ends prior to week 9, then every player will be given a refund. However, if week 9 completes and then the season ends early, all prizes will be paid out at the point just like the season completed.','','',NULL,'BILLY','BILLY'),
        ('FAQ',20,'I entered my email and now I see a message that says "Please check your email to sign in."  What do I do now?','We are no longer storing passwords as a security enhancement. To complete sign in, please open your email account you entered and click the "Sign In" button found in the email we sent you.','Login/Registration','','BILLY','BILLY'),
        ('FAQ',90,'Registration is over for this year, please try again next season.','You may register up until the start of week 3. If you are already registered, please sign in with your previous sign in method (i.e. email, Google, or Twitter).  If you find this to be an error, please contact us at the email at the bottom of this page.','Login/Registration','','BILLY','BILLY'),
        ('FAQ',100,'I am receiving an error that says "It looks like you haven''t linked your account yet."','This is because you originally signed up with a different account (email, Google or Twitter).  Please login using your original account and then once in, you can link additional accounts by using the Edit My Profile screen.','Login/Registration',NULL,'BILLY','BILLY'),
        ('FAQ',10,'What’s my login password? I forgot it.','Fear not. The site is designed so you do not need a password, the only requirement is to have access to your email. Type in your email, and a new email will be sent to you momentarily, then click the green “Sign In” button within that email.','Login/Registration',NULL,'BRIAN','BRIAN'),
        ('FAQ',10,'How do I get started?','Create an account using a preferred email. A new email will be sent to your account (either you are a returning player or a new player that needs to be accepted into the pool by the admins). Click the green button to register in the email. Fill out your information on the “Finish Registration” screen and click save. If you need to go back and edit the account information at a later time, you can access this on your menu under My account -> Edit My Profile. Additionally, on the Edit My Profile screen, you can select which notifications you want and set up other options such as auto picks.','General',NULL,'BRIAN','BRIAN'),
        ('FAQ',20,'I received an error message or something that said "Something went wrong".  What do I do?','If an error occurs, the following steps should be taken, in order until resolved.  1. Try the action that caused the error again.  It might have been a brief network issue that caused it.  2. Try reloading your browser.  3. Close all your open tabs and/or restart your browser.  4.  Try a different browser/device.  5.  If the issue still occurs, contact us using either the email address at the bottom of this page or the Slack link.','General',NULL,'BRIAN','BRIAN'),
        ('FAQ',10,'I forgot to make my survivor pick and the week has already started.','Double doink! Unfortunately, you are now out as we have to be fair to the other players who made their picks on time. Make sure to take advantage of the reminder notifications in your My Account > Edit My Profile page to prevent missing out on other picks or future survivor pools.','Survivor Pool',NULL,'BRIAN','BRIAN'),
        ('FAQ',20,'Who wins the survivor pool?','Each week, players survive or not based on the team they picked winning.  Eventually, either the season ends, or there are no more players left, or only one player left "alive".  If the season ends, all "alive" players split the pot.  If there is only one player "alive", they win first place.  If multiple players go out together so there are no more players left, they will split the pot.','Survivor Pool',NULL,'BRIAN','BRIAN'),
        ('FAQ',30,'My browser tab/title keeps flashing that I have alerts.','Please check the top of your page for any outstanding alerts.  For instance, until you pay your entry fee, you will have a message reminding you how much you owe and when its due by.  Complete whatever the alert is (i.e. paying your entry fee) to get rid of the active alerts.','General',NULL,'BRIAN','BRIAN'),
        ('FAQ',30,'Is there a benefit to registering with email vs. Google vs. Twitter?','Emails use a password-less flow, meaning you will need to enter your address and then check your email for the link to complete sign in each time you sign into the pool.  Google and Twitter both use those services to authenticate you, so you only need to click the button to be signed in.  Which you choose for registering is 100% up to you as you will be given the option after signing in of linking additional services to allow future sign ins.','Login/Registration',NULL,'BRIAN','BRIAN'),
        ('FAQ',40,'I am receiving an error that says "It looks like your email is not valid, please double check it and try again"','This means you have entered an invalid email.  Please double check the spelling closely and try again.','Login/Registration',NULL,'BRIAN','BRIAN'),
        ('FAQ',50,'I entered my email address and double checked it''s correct but still have not received the sign in email link.','If you are sure you entered the correct email address, please give the email a couple minutes to come through.  Additionally, check your spam folder and whitelist our email address (found at the bottom of this screen) if needed.  If you still have not received the email after 5 minutes or so, try to sign in again or contact us at the email below.','Login/Registration',NULL,'BRIAN','BRIAN'),
        ('FAQ',10,'How do I use the Help page?','This page can be used to answer any questions you might have.  The Rules are at the top and commonly asked questions are at the bottom.  You can browse or even search for your answers using the search bar at the top.  In order to view the answers, please click on the caret next to each question to view the green answer text.  If you have questions not found on this page, we want to know!  Simply email us or join our Slack using the links at the bottom of the page.','Help',NULL,'BRIAN','BRIAN'),
        ('FAQ',10,'What should Team Name be?','Anything you want or nothing at all!  This optional field lets you add some color to your profile and will be displayed along with your name on all appropriate screens.  If you leave it blank, it will default to "FIRSTNAME''s Team", where FIRSTNAME is your first name.','Finish Registration',NULL,'BRIAN','BRIAN'),
        ('FAQ',20,'Who should I enter for the "Who referred you to play?" question?','Please enter the name of whomever invited exactly as it is spelled.  This is important for new users so we know who you are.  If you were not invited by anyone or enter their name incorrectly, it may slow your entry into the pool as the admins verify your information.','Finish Registration',NULL,'BRIAN','BRIAN'),
        ('FAQ',30,'How do I enter/leave the survivor pool?','You may enter or leave survivor pool up until the start of the first game of the season.  You can enter via the Finish Registration screen when signing up, or by using the link in the menu under Survivor.  Unfortunately, users are not permitted to enter or leave the Survivor pool once the kickoff for the first game of the season has occurred.','Survivor Pool',NULL,'BRIAN','BRIAN'),
        ('FAQ',30,'Can I change my payment account later?','Yes, you can always edit this account under the My Account -> Edit My Profile screen.  Please be sure to enter this information accurately as if we cannot pay you using the information you enter, you will not be paid until it is fixed.  All payouts will be done at the season so it is critical you fill out this information accurately to avoid missing any prizes won throughout the season.','Finish Registration',NULL,'BRIAN','BRIAN'),
        ('FAQ',10,'What are Auto Picks?','If a game starts and you have made your pick, any remaining auto picks you have can automatically make the selection for you so you don''t lose out on points.  This can be made based on home, away or random.  Everyone gets 3 total for the entire season and they do not replenish.','Edit My Profile',NULL,'BRIAN','BRIAN'),
        ('FAQ',20,'What is the Auto Picks Strategy?','This controls how the system makes any auto picks on your behalf.  Home selects the team playing at home, Away selects the visiting team, and Random randomly chooses the home or away team.','Edit My Profile',NULL,'BRIAN','BRIAN'),
        ('FAQ',30,'Why are the SMS notification options disabled for me?','In order to enable SMS notifications, you must enter a valid SMS-capable phone number on your profile first.  Once this has been entered, the toggles will be enabled and allow you to turn on SMS notifications for each notification type you choose.','Edit My Profile',NULL,'BRIAN','BRIAN'),
        ('FAQ',40,'What does "Send how many hours before?" mean?','For notification types this applies to, this value indicates how many hours before the first kickoff of each week to send the notification when applicable.  For instance, if you enter 24, 24 hours before the first kickoff of the week your picks will be checked and if you have not submitted yet, you will then receive a notification reminding you to do so.','Edit My Profile',NULL,'BRIAN','BRIAN'),
        ('FAQ',50,'Why are you asking for a phone number?','This completely optional field is only used to send you SMS notifications, if you enable them.  You can choose to completely omit entering this or, if you do enter it, can choose to never turn on SMS notifications if you don''t wish to ever receive any text messages from us.','Edit My Profile',NULL,'BRIAN','BRIAN'),
        ('FAQ',30,'How will I know if my entry fee payment was received?','All payments will show up on the View Payments screen. Additionally, if you are all paid up, your alert to pay will go away.  Please give us up to 24 hours, however if after this the alert does not go away and your View Payments screen does not reflect your payment, please contact us.','View Payments',NULL,'BRIAN','BRIAN'),
        ('FAQ',20,'When will I be paid for my winnings?','All payouts occur at the end of the football season, around super bowl weekend.  If you still have not been paid once the super bowl is over, please contact us.  Additionally, you can always see once you should have received your payment as this will also be recorded on the View Payments screen.','View Payments',NULL,'BRIAN','BRIAN'),
        ('FAQ',10,'Why do my winnings show as $0?','Prize amounts are not set until everyone in the pool has paid their entry fee.  Until everyone pays and the prizes are set, winnings show as $0.  Rest assured that once prizes are set, they will show up correctly for all winnings in the past and future.','View Payments',NULL,'BRIAN','BRIAN'),
        ('FAQ',20,'How are rankings determined for weekly/overall?','All rankings are ordered first by highest number of points, and then total number of correct games picks.  For weekly ranks, further ties are ordered by the tiebreaker score.  Closest to the actual last game of the week''s score without going over wins.  If both players are over, then the closest to the score wins.  In the event that both players have the same tiebreaker score, they tie.','Dashboard',NULL,'BRIAN','BRIAN'),
        ('FAQ',10,'Why can''t I view others'' picks?','For each week, you can only view rankings and all picks once you have submitted your picks for that week.','Dashboard',NULL,'BRIAN','BRIAN'),
        ('FAQ',50,'Why is there a football icon next to a team''s score?','This indicates this team currently has possession of the ball.','NFL Scoreboard',NULL,'BRIAN','BRIAN'),
        ('FAQ',40,'Why is a team''s name in green?','After the game is over, the winner is highlighted in green and the loser gets greyed out to visually indicate game results.','NFL Scoreboard',NULL,'BRIAN','BRIAN'),
        ('FAQ',30,'Why is a team''s name and logo greyed out?','After the game is over, the winner is highlighted in green and the loser gets greyed out to visually indicate game results.','NFL Scoreboard',NULL,'BRIAN','BRIAN'),
        ('FAQ',20,'Why is a team''s name in red?','Red means that this time is currently in the redzone.','NFL Scoreboard',NULL,'BRIAN','BRIAN'),
        ('FAQ',10,'Are these scores live?','These games are all updated every minute and the screen should automatically refresh.  If you think the scores are no longer updating, please try refreshing the page.','NFL Scoreboard',NULL,'BRIAN','BRIAN'),
        ('FAQ',20,'What does "No Pick" mean?','Unfortunately, this means this player failed to submit a pick for the week and are therefore out.  Remember that all survivor picks must be set prior to the first game of the week starting.','View Survivor Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',10,'Why are some player''s names highlighted in green and some in red?','If a player is currently "alive", they are in green.  All players who are already out are highlighted in red.','View Survivor Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',10,'What is this screen used for?','This screen is used to show all details about your confidence pool picks for the week.  You can view all games for the week, any picks you have made, as well as results once the games have been played.  You can also see statistics at the top of the screen such as max possible points and max possible games.','View My Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',50,'What is the difference between Live Results and What If?','Live Results show the actual current results for the week, including all picks, points and ranks for all players.  What If also shows all this data, however it allows you to modify what did happen or what will happen to test out various scenarios.','View All Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',40,'Can I make additional What If changes without resetting and starting over?','For sure, just click the big blue What If button to reopen the What If modal and further change the game results as much as you want!','View All Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',30,'How do I reset the What If changes I made?','You can switch back to the Live Results at any time using the button dropdown at the top.  This resets all games to their actual results, effectively resetting any changes you made.','View All Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',20,'How do I see the possible results for the week?','The button at the top can be toggled using the dropdown between Live Results and What If.  On What If, you can change all game results to test out various scenarios for the week.','View All Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',10,'What does PE, GC, MT and AS mean on mobile?','These are abbreviations for values seen on desktop.  They stand for Points Earned, Games Correct, My Tiebreaker Score, and Actual Score.','View All Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',80,'When are survivor picks due?','Each week''s survivor pick is due prior to the kickoff of the first game of that week.  Once the week has started, any players who have missed entering their pick are out and all players'' picks can be viewed.','Make Survivor Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',70,'How do I submit my survivor pick?','To make things as easy as possible, simply clicking the team is all that is required to submit your pick.  You can always change your pick up until the week starts if you change your mind.','Make Survivor Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',60,'Can I unselect a team?','You can always change your selection up until the week has started, however, there is no way to unselect a team once selected.','Make Survivor Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',50,'Why are some teams missing from the selection?','The view only shows the games for the current week, so some teams are hidden at the bottom if they are on bye.  These teams cannot be chosen, however, they are listed just so it''s clear which teams are on bye for a given week.','Make Survivor Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',40,'Why can''t I select a team?','Each team can only be selected once for the season so if a team is highlighted with a number in the top corner, it has already been chosen and as such, cannot be chosen again.','Make Survivor Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',30,'How do I view more details about a team or game?','For each game, there is an info icon in the top right corner.  Clicking this switches to a detail view where you can view more details about the game and each team.  Once done, clicking it a second time closes the detail view.','Make Survivor Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',20,'What are the numbers for on the team cards?','The number in the corner is what week this team was selected.  Since each team can only be selected once per season, it helps indicate which teams have already been chosen and in what week they were used.','Make Survivor Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',10,'How do I make my survivor pick?','On this screen, there are a list of teams for the week.  In each game are the teams playing, and you can click on one of those teams to select it as your choice for the week.  Once selected, it will highlight and show the current week in the corner to indicate it as your pick for the week.','Make Survivor Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',110,'Can you change your picks after submitting them, even if its before the week has started?','Unfortunately, no.  Once you have submitted your picks, no more changes are allowed.  This is because you are allowed to see everyone else''s picks at that point and so can no longer change your own picks.','Make Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',100,'Why can''t I change/pick a game?','Games can only be picked up until their kickoff time.  If a game is highlighted in dark blue or red, the game has already started and as such, can no longer be changed.','Make Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',90,'How do I undo one pick?','While the Reset button can be used to undo all your picks for a week, you can simply drag a point value off of one game back to the top point bank to unset one single pick for the week.','Make Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',80,'How do I make my picks?','Drag each point value from the top point bank to the team you expect to win.  Since the points are awarded if you are correct, you will want to put the highest point totals on games you feel certain of and the lowest point values on games you feel the least certain on.','Make Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',70,'How can I view more details about each game or team?','You can click on the team logo or name to open the detail view for a game.  This displays additional information such as each team''s record, previous games, and the game''s spread.  Simply click back on the logo or team name again to close the detail view once done.','Make Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',60,'What is the Tiebreaker Score used for?','For the weekly rankings, players are ordered first by points earned and then by games correct.  In the event that 2 players have the same points earned and games correct, this tiebreaker score is used to break the tie.  The way it works is the final game of the week''s total score (home score plus visitor score) is used to compare.  The closest player without going over wins.  If both players are over, the closest score wins.  If both players have entered the same tiebreaker score, they end up tied.','Make Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',50,'What does the Submit button do?','This button submits your picks for the week.  Once submitted, no more changes can be made to your picks.  Additionally, you can then see everyone else''s picks as well under the View All Picks page.','Make Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',40,'What does the Save button do?','This button saves your current progress so you can come back later to finish.  Note that this does not submit your picks so it is important you still remember to do that before the week ends.','Make Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',30,'Does the Auto Pick button subtract from the 3 auto picks everyone gets for the season?','No, these 2 auto picks are completely different.  The auto picks on the Edit My Profile screen are related to the picks you miss.  The auto picks on the Make Picks screen are just for filling your picks for you.  This button can be used as often as you want, including every single week if so desired.','Make Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',20,'What does the Auto Pick button do?','Clicking this button brings up 3 options: Home, Away, or Random.  Choosing one of these options fills all your unpicked picks with randomly selected points.  Note that this will not touch any picks you have already made or games that have already started.','Make Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',10,'What does the Reset button do?','This button resets all your picks back to the point bank.  If you want to start over, click this button.','Make Picks',NULL,'BRIAN','BRIAN'),
        ('FAQ',120,'What happens if a game ends in a tie?','If a game ends in a tie, everyone loses that game regardless of which team was picked.','Make Picks',NULL,'BRIAN','BRIAN')`);
	}

	public async down (queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`truncate table SupportContent`);
	}
}
