# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy Node.js project to Azure Function App - aswnn-nfl

on:
  push:
    branches:
      - develop
      - main

env:
  AZURE_FUNCTIONAPP_NAME: aswnn-nfl
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "azure"
  NODE_VERSION: "14.x"

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Resolve Project Dependencies Using Npm"
        shell: pwsh
        run: |
          npm ci
          npm run build:azure
          Move-Item node_modules ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/node_modules

      - name: Set environment variables
        run: |
          switch ("${GITHUB_REF}")
          {
            "refs/heads/main" {$DEPLOYMENT_SLOT = ""; Break}
            "refs/heads/develop" {$DEPLOYMENT_SLOT = "dev"; Break}
            default {$DEPLOYMENT_SLOT = "INVALID"; Break}
          }
          echo "DEPLOYMENT_SLOT=${DEPLOYMENT_SLOT}"
          echo "DEPLOYMENT_SLOT=${DEPLOYMENT_SLOT}" >> $GITHUB_ENV

      - name: "Run Azure Functions Action"
        if: ${{ env.DEPLOYMENT_SLOT != 'INVALID' }}
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: ${{ env.DEPLOYMENT_SLOT }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
