# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy Node.js project to Azure Function App - aswnn-nfl

on:
  push:
    branches:
      - develop
      - main

env:
  NODE_VERSION: "14.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: "Install Azure CLI"
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: "Login via Azure CLI"
        env:
          AZURE_APP_PASSWORD: ${{ secrets.AZURE_APP_PASSWORD }}
        run: az login -u bduff9@gmail.com -p $AZURE_APP_PASSWORD

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Resolve Project Dependencies Using Npm"
        run: npm ci

      - name: "Deploy dev using Azure CLI"
        if: github.ref == 'refs/heads/develop'
        run: npm run deploy:azure:dev

      - name: "Deploy prod using Azure CLI"
        if: github.ref == 'refs/heads/main'
        run: npm run deploy:azure
